name: sfppy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy>=1.21.0
    - matplotlib>=3.4.0
    - scipy>=1.7.0
    - pandas>=1.3.0
    - openpyxl>=3.0.10
    - pillow>=8.0.0
